export const AUTH_INPUT_CHANGE = "auth input change";
export const AUTH_BEGIN = "auth begin";
export const AUTH_SUCCESS = "auth success";
export const AUTH_FAILURE = "auth failure";
export const FETCH_IDEAS = "fetch ideas";
export const IDEA_INPUT_CHANGE = "idea input change";
export const NEW_IDEA = "new idea";
export const EDIT_IDEA = "edit idea";
export const DELETE_IDEA = "delete idea";